---
- name: Install dependencies via apt
  apt:
    name: "{{ item }}"
    cache_valid_time: 86400
    update_cache: yes
  with_items:
    - python-pip

- name: Install dependencies via pip
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items:
    - name: docker-py
      version: 0.6.0

- name: Check for drone
  stat:
    path: /usr/local/bin/drone
  register: drone_stat

- name: Determine if Drone should be installed
  set_fact:
    install_drone: "{{ not drone_stat.stat.exists or upgrade_drone|default(False)|bool == True }}"

- name: Download drone.deb
  get_url:
    url: http://downloads.drone.io/master/drone.deb
    dest: /tmp/drone.deb
    force: "{{ install_drone|default(False)|bool }}"
  register: drone_get

- name: Install drone.deb
  apt:
    deb: /tmp/drone.deb
  register: drone_dpkg
  when: install_drone|default(False)|bool
  notify:
   - restart drone

- name: Install required drone images
  docker:
    image: "{{ item }}"
    state: present
  with_items:
    - bradrydzewski/ubuntu
    - bradrydzewski/base

- name: Install optionally specified drone images
  docker:
    image: "{{ item.name }}:{{ item['tag']|default('latest') }}"
    state: "{{ item['state']|default('present') }}"
  with_items: drone_images

- name: Install sqlite3 for drone configuration
  apt:
    name: "{{ item }}"
    cache_valid_time: 86400
    update_cache: yes
  with_items:
    - "sqlite3"
    - "libsqlite3-dev"

- name: Template sqlite file for drone database configuration
  template:
    src: drone.sql.j2
    dest: /etc/drone/drone.sql
    owner: root
    group: root
    mode: 0600

- name: Template TOML file for drone daemon configuration
  template:
    src: drone.toml.j2
    dest: /etc/drone/drone.toml
    owner: root
    group: root
    mode: 0600
  notify:
    - restart drone

- name: Hash tables to validate change
  shell: "sqlite3 /var/lib/drone/drone.sqlite 'SELECT * FROM users;' | md5sum"
  register: drone_before_hash
  changed_when: False

- name: Configure drone database settings
  shell: "sqlite3 /var/lib/drone/drone.sqlite '.read /etc/drone/drone.sql' && sqlite3 /var/lib/drone/drone.sqlite 'SELECT * FROM users;' | md5sum"
  register: drone_after_hash
  changed_when: drone_after_hash.stdout|trim != drone_before_hash.stdout|trim

- name: Ensure drone is started
  service:
    name: drone
    state: started
    enabled: yes
